# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'MoviePlay' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'Reusable'
  pod 'Kingfisher'
  pod 'youtube-ios-player-helper' 
  # Pods for MoviePlay

end
